apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-homelab-cert
  namespace: cattle-system
spec:
  secretName: rancher-homelab-tls
  duration: 8760h
  renewBefore: 2160h
  commonName: rancher.homelab.local
  dnsNames:
  - rancher.homelab.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer

