# argocd-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
  namespace: argocd
spec:
  secretName: argocd-tls
  duration: 8760h
  renewBefore: 2160h
  commonName: argocd.homelab.local
  dnsNames:
  - argocd.homelab.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer

