# K3s Upgrade Configuration
# Note: Target version is determined from k3s_setup/vars/main.yml:
#   - If k3s_upgrade_version is set, it will be used for upgrade
#   - If k3s_upgrade_version is empty, k3s_version will be used
# Upgrade will only happen if current version < target version
# If current version >= target version, upgrade will be skipped

# Upgrade Settings
upgrade_drain_timeout: 600  # Drain timeout in seconds (increased for PVC-heavy workloads)
upgrade_drain_grace_period: 120  # Grace period for pod termination (seconds)
upgrade_wait_for_pods: 60   # Wait time for pods to stabilize after upgrade (seconds)
upgrade_force: false         # Force upgrade even if versions match

