apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-longhorn-cert
  namespace: longhorn-system
spec:
  secretName: homelab-longhorn-tls
  duration: 8760h
  renewBefore: 2160h
  commonName: longhorn.homelab.local
  dnsNames:
  - longhorn.homelab.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
