---
# ============================
# Install kube-prometheus-stack (Prometheus + Grafana + Alertmanager)
# ============================

- name: Find home directory for UID 1000
  command: getent passwd 1000
  register: getent_passwd_output
  changed_when: false
  when: "'master' in group_names"

- name: Set home directory variable
  set_fact:
    user_home_directory: "{{ getent_passwd_output.stdout.split(':')[5] }}"
  when:
    - "'master' in group_names"
    - getent_passwd_output.stdout != ""

- name: Define the user name with UID 1000
  command: getent passwd 1000
  register: getent_passwd_result
  changed_when: false

- name: Set user name variable from getent passwd output
  set_fact:
    uid_1000_user: "{{ getent_passwd_result.stdout.split(':')[0] }}"
  when: getent_passwd_result.stdout != ''

- name: Check if monitoring namespace exists
  command: kubectl get namespace monitoring
  register: monitoring_namespace_exists
  failed_when: false
  changed_when: false
  when: "'master' in group_names"

- name: Check if kube-prometheus-stack Helm release exists
  ansible.builtin.command:
    cmd: helm list -n monitoring -q
  register: kube_prometheus_stack_helm_release
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ uid_1000_user }}"
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when:
    - "'master' in group_names"
    - inventory_hostname == 'master-1'

- name: Check if Prometheus Helm repository is already added
  ansible.builtin.command:
    cmd: helm repo list
  register: helm_repo_list
  ignore_errors: true
  become: true
  become_user: "{{ uid_1000_user }}"
  when: "'master' in group_names"

- name: Fail if helm repo list failed for reasons other than no repositories
  ansible.builtin.fail:
    msg: "Failed to list Helm repositories: {{ helm_repo_list.stderr }}"
  when:
    - "'master' in group_names"
    - helm_repo_list.rc != 0
    - "'Error: no repositories to show' not in helm_repo_list.stderr"

- name: Extract Helm repository names
  ansible.builtin.shell: |
    echo "{{ helm_repo_list.stdout }}" | awk 'NR > 1 {print $1}'
  register: helm_repo_names
  when: "'master' in group_names"

- name: Check if Prometheus Helm repository is already present
  ansible.builtin.set_fact:
    prometheus_repo_present: "{{ 'prometheus-community' in helm_repo_names.stdout }}"
  when: "'master' in group_names"

- name: Debug if Prometheus Helm repository is present
  ansible.builtin.debug:
    msg: "Prometheus Helm repository is present: {{ prometheus_repo_present }}"
  when: "'master' in group_names"

- name: Add Prometheus Helm repository (with retries)
  command: helm repo add prometheus-community {{ helm_repo_prometheus }}
  become: true
  become_user: "{{ uid_1000_user }}"
  register: add_prometheus_repo
  retries: 3
  delay: 10
  until: add_prometheus_repo.rc == 0
  when:
    - "'master' in group_names"
    - not prometheus_repo_present

- name: Debug message if Prometheus Helm repository is already present
  ansible.builtin.debug:
    msg: "Prometheus Helm repository is already added."
  when:
    - "'master' in group_names"
    - prometheus_repo_present

- name: Update Helm repository list
  ansible.builtin.command:
    cmd: helm repo update
  become: true
  become_user: "{{ uid_1000_user }}"
  when: "'master' in group_names"

- name: Count the number of master nodes
  set_fact:
    master_count: "{{ groups['master'] | length | int }}"
  when: "'master' in group_names"
  run_once: true

- name: Install kube-prometheus-stack Helm chart (HA mode - 3+ masters)
  ansible.builtin.command:
    cmd: helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace -f {{ user_home_directory }}/my-charts/grafana/kube-prometheus-stack-values.yml -f {{ user_home_directory }}/my-charts/grafana/kube-prometheus-stack-values-master-only.yml
  become: true
  become_user: "{{ uid_1000_user }}"
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when:
    - inventory_hostname == 'master-1'
    - monitoring_namespace_exists.rc != 0
    - (kube_prometheus_stack_helm_release.stdout | default('') | trim) == ''
    - (master_count | default(0) | int) >= 3

- name: Install kube-prometheus-stack Helm chart (Single Master)
  ansible.builtin.command:
    cmd: helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace -f {{ user_home_directory }}/my-charts/grafana/kube-prometheus-stack-values.yml -f {{ user_home_directory }}/my-charts/grafana/kube-prometheus-stack-values-single-master.yml -f {{ user_home_directory }}/my-charts/grafana/kube-prometheus-stack-values-master-only.yml
  become: true
  become_user: "{{ uid_1000_user }}"
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when:
    - inventory_hostname == 'master-1'
    - monitoring_namespace_exists.rc != 0
    - (kube_prometheus_stack_helm_release.stdout | default('') | trim) == ''
    - (master_count | default(0) | int) < 3

- name: Wait for kube-prometheus-stack pods to be in Running state
  command: kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath='{.items[*].status.phase}'
  register: grafana_pod_status
  until: grafana_pod_status.stdout.find('Running') != -1
  retries: 15
  delay: 30
  when:
    - inventory_hostname == 'master-1'
    - monitoring_namespace_exists.rc != 0
    - (kube_prometheus_stack_helm_release.stdout | default('') | trim) == ''

- name: Wait for Prometheus pods to be in Running state
  command: kubectl get pods -n monitoring -l app.kubernetes.io/name=prometheus -o jsonpath='{.items[*].status.phase}'
  register: prometheus_pod_status
  until: prometheus_pod_status.stdout.find('Running') != -1
  retries: 15
  delay: 30
  when:
    - inventory_hostname == 'master-1'
    - monitoring_namespace_exists.rc != 0
    - (kube_prometheus_stack_helm_release.stdout | default('') | trim) == ''

- name: Wait for Grafana PVC to be bound
  command: kubectl get pvc -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath='{.items[*].status.phase}'
  register: grafana_pvc_status
  until: grafana_pvc_status.stdout.find('Bound') != -1
  retries: 10
  delay: 30
  when: inventory_hostname == 'master-1'

- name: Wait for Prometheus PVC to be bound
  command: kubectl get pvc -n monitoring -l app.kubernetes.io/name=prometheus -o jsonpath='{.items[*].status.phase}'
  register: prometheus_pvc_status
  until: prometheus_pvc_status.stdout.find('Bound') != -1
  retries: 10
  delay: 30
  when: inventory_hostname == 'master-1'

- name: Apply Grafana ingress config
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/grafana/cert/homelab.grafana.yml
  become: true
  become_user: "{{ uid_1000_user }}"
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when:
    - inventory_hostname == 'master-1'
    - monitoring_namespace_exists.rc != 0
    - cert_manager_install | default(false)

- name: Apply homelab.grafana certificate
  ansible.builtin.command:
    cmd: kubectl apply -f {{ user_home_directory }}/my-charts/grafana/cert/homelab-grafana-certificate.yml
  become: true
  become_user: "{{ uid_1000_user }}"
  environment:
    KUBECONFIG: "{{ user_home_directory }}/.kube/config"
  when:
    - inventory_hostname == 'master-1'
    - monitoring_namespace_exists.rc != 0
    - cert_manager_install | default(false)

- name: Retrieve Grafana admin password
  ansible.builtin.shell: >
    kubectl get secret --namespace monitoring kube-prometheus-stack-grafana -o jsonpath="{.data.admin-password}" | base64 --decode
  register: grafana_admin_password
  when: inventory_hostname == 'master-1'

- name: Display Grafana admin password
  debug:
    msg: "Grafana admin password: {{ grafana_admin_password.stdout }}"
  when: inventory_hostname == 'master-1'

- name: Retrieve Grafana admin user
  ansible.builtin.shell: >
    kubectl get secret --namespace monitoring kube-prometheus-stack-grafana -o jsonpath="{.data.admin-user}" | base64 --decode
  register: grafana_admin_user
  when: inventory_hostname == 'master-1'

- name: Display Grafana admin user
  debug:
    msg: "Grafana admin user: {{ grafana_admin_user.stdout }}"
  when: inventory_hostname == 'master-1'

- name: Retrieve Prometheus service URL
  ansible.builtin.shell: >
    kubectl get svc -n monitoring kube-prometheus-stack-prometheus -o jsonpath="{.spec.clusterIP}"
  register: prometheus_server_ip
  when: inventory_hostname == 'master-1'

- name: Display Prometheus service IP address
  debug:
    msg: "Prometheus service IP address: {{ prometheus_server_ip.stdout }}"
  when: inventory_hostname == 'master-1'

- name: Display Prometheus data URL
  debug:
    msg: "Prometheus data URL: {{ prometheus_data_url }}"
  when: inventory_hostname == 'master-1'
