# Variables for adding extra nodes to existing K3s cluster
# 
# IMPORTANT: This role uses k3s_install_url and k3s_version from k3s_setup/vars/main.yml
# These variables are automatically loaded via vars_files in add_node.yml playbook.
# 
# DO NOT define k3s_install_url or k3s_version here unless you want to override them.
# If you need to use a different version for new nodes, uncomment and set below:
#
# k3s_version: "v1.32.9+k3s1"  # Override version (not recommended - should match cluster)
# k3s_install_url: https://get.k3s.io  # Override install URL (usually not needed)

